dist:
  module: github.com/lumigo-io/lumigo-otel-collector-contrib
  name: lumigo-collector
  description: Lumigo OpenTelemetry collector
  otelcol_version: "0.107.0"
  version: "0.107.0-dev"
  output_path: cmd/otelcontribcol

exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awskinesisexporter v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.107.0"
  - gomod: "go.opentelemetry.io/collector/exporter/loggingexporter v0.107.0"
  - gomod: "go.opentelemetry.io/collector/exporter/otlphttpexporter v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.107.0"

extensions:
  - gomod: "github.com/lumigo-io/lumigo-otel-collector-contrib/extension/lumigoauthextension v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.107.0"

receivers:
  - gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.107.0"

processors:
  - gomod: "go.opentelemetry.io/collector/processor/batchprocessor v0.107.0"
  - gomod: "github.com/lumigo-io/lumigo-otel-collector-contrib/processor/k8seventsenricherprocessor v0.107.0"
  - gomod: "github.com/lumigo-io/lumigo-otel-collector-contrib/processor/redactionbykeyprocessor v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.107.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.107.0"

replaces:
  - github.com/lumigo-io/lumigo-otel-collector-contrib/internal/k8sconfig => ../../internal/k8sconfig
  - github.com/lumigo-io/lumigo-otel-collector-contrib/extension/lumigoauthextension => ../../extension/lumigoauthextension
  - github.com/lumigo-io/lumigo-otel-collector-contrib/processor/k8seventsenricherprocessor => ../../processor/k8seventsenricherprocessor
  - github.com/lumigo-io/lumigo-otel-collector-contrib/processor/redactionbykeyprocessor => ../../processor/redactionbykeyprocessor
  - github.com/openshift/api v3.9.0+incompatible => github.com/openshift/api v0.0.0-20210521075222-e273a339932a
